version: "3.1"
services:
  notes-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  notes-redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - 6379:6379
    volumes:
      - "./docker/redis/redis-data:/var/lib/redis"
      - "./docker/redis:/usr/local/etc/redis/redis.conf"
